language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sonarqube:
    branches:
      - desenv-vlouzada

jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube: true

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

script: 
 - phpunit tests/Teste.php
 - sonar-scanner

notifications:
    email: false
    slack: vlouzada-vvidigal:MgvOM0vlrNNiBBfMOJJWE8Jp
