language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

addons:
  srcclr: true
script: phpunit tests/Teste.php

notifications:
    email: false
    slack: vlouzada-vvidigal:MgvOM0vlrNNiBBfMOJJWE8Jp
